# Generated by Django 5.0.2 on 2024-03-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tables',
        ),
    ]
